apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test-pod
spec:
  containers:
  - name: main-container
    image: radial/busyboxplus:curl
    #image: radial/busyboxplus:curl
    command: ['sh', '-c', 'while true; do curl localhost:8080; sleep 5; done']

  - name: ambassador-container
    image: haproxy:2.4
    volumeMounts:
    - name: config 
      mountPath: /usr/local/etc/haproxy/
  #  command:
  
  volumes: 
  - name: config 
    configMap:
      name: haproxy-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    frontend ambassador
      bind *:8080
      default_bankend ambassador_service_svc
    bankend ambassador_service_svc
      server svc ambassador-service-svc:8081