apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: alpha-namespace
spec:
  hard:
    pods: 2
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 3Gi