apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ckad-exam
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: core-pod
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
        ports:
        - containerPort: 80
